# PersistentVolume (PV) 정의 - 볼륨 제공자
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: 1Gi # 1GB의 저장소 제공
  accessModes:
    - ReadWriteOnce # 단일 노드에서만 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Retain # PVC 삭제 시에도 데이터 유지 (Retain, Delete, Recycle 가능)
  storageClassName: manual
  hostPath:
    path: "/docker/volume/mariadb" # 실제 물리적 저장 위치
    type: DirectoryOrCreate # 폴더가 없으면 자동 생성
---
# PersistentVolumeClaim (PVC) 정의 - 볼륨 사용자
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual # PV와 동일한 StorageClass 설정.
  volumeName: mariadb-pv # 제공자 연결

---
# StatefulSet 상태유지 서비스 정의
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb"
  replicas: 1 # 일반적으로 단일 노드 운영
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD # MariaDB 루트 계정 비밀번호 설정
              value: "rootpassword"
            - name: MYSQL_DATABASE # 생성할 기본 DB
              value: "testdb"
            - name: MYSQL_USER # MariaDB에서 사용할 일반 계정
              value: "testuser"
            - name: MYSQL_PASSWORD
              value: "testpassword"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage # 아래 volumes에서 정의한 PVC 사용
              mountPath: /var/lib/mysql # MariaDB 컨테이너 내부의 데이터 저장소
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc # 앞서 정의한 볼륨 사용자를 지정. (mariadb-pv와 연결하도록 설정됨)
