# PersistentVolume (PV) 정의
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv # PV의 이름
spec:
  capacity:
    storage: 1Gi # 1GB의 저장소 제공
  accessModes:
    - ReadWriteOnce # 단일 노드에서만 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Retain # PVC 삭제 시에도 데이터 유지
  storageClassName: manual
  hostPath:
    path: "/docker/volume/postgres" # 실제 물리적 저장 위치 (서버 내부 디렉토리)
    type: DirectoryOrCreate # 폴더가 없으면 자동 생성
---
# PersistentVolumeClaim (PVC) 정의
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc # PVC의 이름
spec:
  accessModes:
    - ReadWriteOnce # 단일 노드에서 사용 가능
  resources:
    requests:
      storage: 1Gi # 1GB의 볼륨 요청
  storageClassName: manual # PV와 동일한 StorageClass 설정.
  volumeName: postgres-pv # 특정 PV와 연결 (자동 매칭)

---
# StatefulSet 정의 (PostgreSQL 배포)
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1 # PostgreSQL은 일반적으로 단일 노드로 운영
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              value: "testdb"
            - name: POSTGRES_USER
              value: "testuser"
            - name: POSTGRES_PASSWORD
              value: "testpassword"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage # 아래 volumes에서 정의한 PVC 사용
              mountPath: /var/lib/postgresql/data # PostgreSQL 컨테이너 내부 데이터 저장소
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc # 위에서 정의한 PVC 사용 (postgres-pv와 연결됨)
